### ISSUE TITLE
🗣 Dockerize Named Poll Scraper

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1021]

**Comment by ulfgebhardt** [comment]
The coresponding Repo is: https://github.com/demokratie-live/namedPollDockerTest

Advantages of this approche:
- Control over the machine running scraping process
- Since its a virtual machine it can be scaled on hardware
- Easy restartability

Disadvantages:
- More Hardware use
- No dynamic control over starttime(recompile required)
- Possible duplicate runs of the same job
- Migration & Model Code duplication
- Responsibility of migration unclear
