### ISSUE TITLE
[Potential bug] Votes cannot be changed

### ISSUE THREAD

**Issue by alexschwarz89** [demokratie-live/democracy-client#197]
**Description:**

If voted, one can not change his mind. **Wanted behaviour?**

**Expected Behaviour:**

If i click the "thumbs up" icon after i've voted for "thumbs down" my vote should change. 

**App-Version:** 0.3.5

**Comment by ulfgebhardt** [comment]
Thanks for the Report @alexschwarz89,

yes this is a wanted behavior and also has technical reasons.
- once voted you cannot take back your vote
- since we do not save your vote directly - only the sum of all votes & and that you have voted - to protect your privacy

You are also right tho - we will let the User confirm his/her vote before locking it in. We will furthermore show the User Arguments from the Discussion, which are against his proposed vote in oder to make him think abaut it again.

![image](https://user-images.githubusercontent.com/1238238/38077317-e2483004-3338-11e8-8b6f-cccac124d421.png)
User is voting yes and the best 3 contra Arguments are shown.

![image](https://user-images.githubusercontent.com/1238238/38077388-1d24ef64-3339-11e8-8b16-6d655f579ff0.png)
User is voting no and the best 3 pro Arguments are shown.

![image](https://user-images.githubusercontent.com/1238238/38077349-fdf321ba-3338-11e8-9a5d-78e4a5868c85.png)
User is voting abstain and the best Arguments of both sides are shown

This feature will be part of the Prototyp

Do you think that solves the Issue?
